//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piti2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatus
    {
        public Estatus()
        {
            this.Servicios = new HashSet<Servicios>();
            this.Subdominios = new HashSet<Subdominios>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int estatusID { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaagregado { get; set; }
        public System.DateTime fechamodificado { get; set; }
    
        public virtual ICollection<Servicios> Servicios { get; set; }
        public virtual ICollection<Subdominios> Subdominios { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
