//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piti2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int pagosID { get; set; }
        public int serviciosID { get; set; }
        public System.DateTime fechapago { get; set; }
        public double montopago { get; set; }
    
        public virtual Servicios Servicios { get; set; }
    }
}
