//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piti2013.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PymesFinder : DbContext
    {
        public PymesFinder()
            : base("name=PymesFinder")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Estatus> Estatus { get; set; }
        public DbSet<Pagos> Pagos { get; set; }
        public DbSet<Publicidad> Publicidad { get; set; }
        public DbSet<Pymes> Pymes { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<Subdominios> Subdominios { get; set; }
        public DbSet<TipoPublicidad> TipoPublicidad { get; set; }
        public DbSet<TipoServicio> TipoServicio { get; set; }
        public DbSet<TipoUsuario> TipoUsuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
