//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piti2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Pymes = new HashSet<Pymes>();
        }
    
        public int usuarioID { get; set; }
        public string nombre { get; set; }
        public string apellidopaterno { get; set; }
        public string apellidomaterno { get; set; }
        public string calle { get; set; }
        public int numero { get; set; }
        public Nullable<long> codigopostal { get; set; }
        public Nullable<long> telefono { get; set; }
        public string cuenta { get; set; }
        public string contrasena { get; set; }
        public string correo { get; set; }
        public System.DateTime fechaagregado { get; set; }
        public System.DateTime fechamodificado { get; set; }
        public int tipousuarioID { get; set; }
        public int estatusID { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual ICollection<Pymes> Pymes { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
